[project]
name = "chat-bhandaar"
version = "0.1.0"
description = "A customizable Streamlit chat interface with theme switching, chat history management, and varying assistant response styles."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "openai"
]
