USE_HOST = "ollama"

[openrouter]
API_KEY = "openrouter key here"
BASE_URL = "https://openrouter.ai/api/v1"
MODEL_NAME = "openai/gpt-oss-120b"

[ollama]
API_KEY = ""
BASE_URL = "http://localhost:11434/v1"
MODEL_NAME = "gemma3:1b"
